name = "DocTest"
uuid = "46dad9a9-3424-4f2d-8e99-86af129c7bc8"
authors = ["Alexandre A. Renchon et al."]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
